version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guess-the-pass
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
